#!/bin/sh
#SBATCH --account=epic-ps
#SBATCH --qos=batch
#SBATCH --partition=orion
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=40
#SBATCH --time=120
#SBATCH --job-name="ctest_gnu"
#SBATCH --exclusive

#
source ../../test/machines/orion_gnu.env 

#
ctest
