#!/bin/sh
#SBATCH --account=epic-ps
#SBATCH --qos=batch
#SBATCH --partition=service
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=12
#SBATCH --time=120
#SBATCH --job-name="ctest_gnu"
#SBATCH --exclusive

#
source ./machines/orion_gnu.env 

#
ctest
